<h1>CSGO Project</h1>

In [28]:
import warnings
warnings.filterwarnings("ignore")

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
df = pd.read_csv("./csgo.csv")
df

time_left  ct_score  t_score       map  bomb_planted  ct_health  \
0          175.00       0.0      0.0  de_dust2         False      500.0   
1          156.03       0.0      0.0  de_dust2         False      500.0   
2           96.03       0.0      0.0  de_dust2         False      391.0   
3           76.03       0.0      0.0  de_dust2         False      391.0   
4          174.97       1.0      0.0  de_dust2         False      500.0   
...           ...       ...      ...       ...           ...        ...   
122405      15.41      11.0     14.0  de_train          True      200.0   
122406     174.93      11.0     15.0  de_train         False      500.0   
122407     114.93      11.0     15.0  de_train         False      500.0   
122408      94.93      11.0     15.0  de_train         False      500.0   
122409      74.93      11.0     15.0  de_train         False      375.0   

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0          500.0       0.0      0.0    4000.0  ...                  0.0   
1          500.0     400.0    300.0     600.0  ...                  0.0   
2          400.0     294.0    200.0     750.0  ...                  0.0   
3          400.0     294.0    200.0     750.0  ...                  0.0   
4          500.0     192.0      0.0   18350.0  ...                  0.0   
...          ...       ...      ...       ...  ...                  ...   
122405     242.0     195.0    359.0     100.0  ...                  2.0   
122406     500.0      95.0    175.0   11500.0  ...                  2.0   
122407     500.0     495.0    475.0    1200.0  ...                  4.0   
122408     500.0     495.0    475.0    1200.0  ...                  5.0   
122409     479.0     395.0    466.0    1100.0  ...                  3.0   

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0   
1                           0.0                     2.0   
2                           0.0                     2.0   
3                           0.0                     0.0   
4                           0.0                     0.0   
...                         ...                     ...   
122405                      1.0                     1.0   
122406                      1.0                     0.0   
122407                      3.0                     5.0   
122408                      0.0                     3.0   
122409                      0.0                     2.0   

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0   
1                                0.0                          0.0   
2                                0.0                          0.0   
3                                0.0                          0.0   
4                                0.0                          0.0   
...                              ...                          ...   
122405                           0.0                          0.0   
122406                           0.0                          0.0   
122407                           1.0                          0.0   
122408                           0.0                          0.0   
122409                           0.0                          0.0   

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0   
1                             0.0                       0.0   
2                             0.0                       0.0   
3                             0.0                       0.0   
4                             0.0                       0.0   
...                           ...                       ...   
122405                        0.0                       0.0   
122406                        0.0                       0.0   
122407                        0.0                       5.0   
122408                        0.0     

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object 
 4   bomb_planted                  122410 non-null  bool   
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-nul

In [32]:
df["round_winner"].unique()

array(['CT', 'T'], dtype=object)

In [33]:
#Too many columns and hence the model tend to overfit hence we shall use LDA since it is a supervised model

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])
        print(le.classes_)

['de_cache' 'de_dust2' 'de_inferno' 'de_mirage' 'de_nuke' 'de_overpass'
 'de_train' 'de_vertigo']
['CT' 'T']


In [36]:
df.isnull().sum().sum()

0

In [37]:
df.duplicated().sum()

4962

In [38]:
df.drop_duplicates(inplace = True)

In [39]:
df

time_left  ct_score  t_score  map  bomb_planted  ct_health  t_health  \
0          175.00       0.0      0.0    1         False      500.0     500.0   
1          156.03       0.0      0.0    1         False      500.0     500.0   
2           96.03       0.0      0.0    1         False      391.0     400.0   
3           76.03       0.0      0.0    1         False      391.0     400.0   
4          174.97       1.0      0.0    1         False      500.0     500.0   
...           ...       ...      ...  ...           ...        ...       ...   
122405      15.41      11.0     14.0    6          True      200.0     242.0   
122406     174.93      11.0     15.0    6         False      500.0     500.0   
122407     114.93      11.0     15.0    6         False      500.0     500.0   
122408      94.93      11.0     15.0    6         False      500.0     500.0   
122409      74.93      11.0     15.0    6         False      375.0     479.0   

        ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0            0.0      0.0    4000.0  ...                  0.0   
1          400.0    300.0     600.0  ...                  0.0   
2          294.0    200.0     750.0  ...                  0.0   
3          294.0    200.0     750.0  ...                  0.0   
4          192.0      0.0   18350.0  ...                  0.0   
...          ...      ...       ...  ...                  ...   
122405     195.0    359.0     100.0  ...                  2.0   
122406      95.0    175.0   11500.0  ...                  2.0   
122407     495.0    475.0    1200.0  ...                  4.0   
122408     495.0    475.0    1200.0  ...                  5.0   
122409     395.0    466.0    1100.0  ...                  3.0   

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0   
1                           0.0                     2.0   
2                           0.0                     2.0   
3                           0.0                     0.0   
4                           0.0                     0.0   
...                         ...                     ...   
122405                      1.0                     1.0   
122406                      1.0                     0.0   
122407                      3.0                     5.0   
122408                      0.0                     3.0   
122409                      0.0                     2.0   

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0   
1                                0.0                          0.0   
2                                0.0                          0.0   
3                                0.0                          0.0   
4                                0.0                          0.0   
...                              ...                          ...   
122405                           0.0                          0.0   
122406                           0.0                          0.0   
122407                           1.0                          0.0   
122408                           0.0                          0.0   
122409                           0.0                          0.0   

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0   
1                             0.0                       0.0   
2                             0.0                       0.0   
3                             0.0                       0.0   
4                             0.0                       0.0   
...                           ...                       ...   
122405                        0.0                       0.0   
122406                        0.0                       0.0   
122407                        0.0                       5.0   
122408                        0.0                       4.0   
122409                        0.0  

In [40]:
df["round_winner"].value_counts()

round_winner
1    59941
0    57507
Name: count, dtype: int64

In [41]:
x = df.drop("round_winner", axis = 1)
y = df["round_winner"]

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
sc = StandardScaler()

In [46]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [47]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [50]:
lda = LinearDiscriminantAnalysis()

In [51]:
lda.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [52]:
lda.transform(x_test)

array([[-0.69224519],
       [-0.72926778],
       [ 1.86900733],
       ...,
       [-0.412417  ],
       [ 0.62073932],
       [ 0.70458681]])

In [54]:
#96 columns/features: provides the importance of each feature for each class
lda.coef_

array([[ 1.32450954e-01, -1.28879044e-02,  1.80798217e-02,
        -8.74488465e-02,  2.39884060e-01, -4.43098719e-01,
         3.27612026e-01, -6.05431498e-01,  6.33015335e-01,
        -2.14552694e-01,  1.68532336e-01,  2.93035188e-02,
         7.33365748e-02, -2.68716636e-02, -1.96820416e-01,
         3.65434345e-01, -1.93183010e-01,  6.07498388e-01,
        -2.03626114e-01,  3.76029060e-02, -3.08425645e-01,
         2.55454777e-01, -2.66083060e-16, -5.51711468e-04,
         1.05124538e-02, -6.89279741e-03, -2.86750520e-03,
         1.94754503e-02, -1.37777398e-01,  4.62222702e-02,
        -5.49605719e-16,  1.84596657e-02, -4.97404086e-02,
         1.33798212e-01,  2.07171531e-02, -1.39679188e-01,
        -2.65388545e-16, -1.02104805e-16, -9.72800626e-02,
         4.80591752e-02, -4.53505704e-01,  1.04335981e-01,
        -9.27751790e-03,  1.14628755e-01, -1.59971534e-02,
         7.82742179e-03, -1.42257642e-02,  3.76839157e-02,
         6.27982602e-03, -6.33115926e-03, -1.20967801e-0

In [55]:
# values are close to zero, hence we gonna increase the magnitude of the values|

In [59]:
lda_coef = np.exp(np.abs(lda.coef_))

lda_coef

array([[1.14162302, 1.01297131, 1.01824425, 1.09138643, 1.27110177,
        1.55752608, 1.3876505 , 1.83204256, 1.88328075, 1.23930742,
        1.1835665 , 1.02973709, 1.07609266, 1.02723596, 1.21752537,
        1.44113982, 1.21310478, 1.83583311, 1.22583974, 1.03831884,
        1.36128029, 1.29104863, 1.        , 1.00055186, 1.0105679 ,
        1.00691661, 1.00287162, 1.01966633, 1.14772004, 1.04730717,
        1.        , 1.0186311 , 1.05099823, 1.14316212, 1.02093324,
        1.14990484, 1.        , 1.        , 1.10216901, 1.04923274,
        1.57381987, 1.10997332, 1.00932069, 1.12145703, 1.01612579,
        1.00785814, 1.01432743, 1.03840296, 1.00629959, 1.00635124,
        1.12858857, 1.03998677, 1.        , 1.00782618, 1.01787059,
        1.01507381, 1.02556116, 1.01876817, 1.        , 1.00634069,
        1.        , 1.01024978, 1.00138927, 1.01247098, 1.22364987,
        1.74599191, 1.08728405, 1.02362632, 1.05268431, 1.09877688,
        1.01636601, 1.00128427, 1.01376886, 1.00

In [60]:
lda_coef = lda_coef.flatten() #to convert it to 1d array

In [61]:
df1=pd.DataFrame({'columns':x.columns,'lda_coef':lda_coef})
df1

columns  lda_coef
0                     time_left  1.141623
1                      ct_score  1.012971
2                       t_score  1.018244
3                           map  1.091386
4                  bomb_planted  1.271102
..                          ...       ...
91  t_grenade_incendiarygrenade  1.009694
92    ct_grenade_molotovgrenade  1.010343
93     t_grenade_molotovgrenade  1.104343
94      ct_grenade_decoygrenade  1.000688
95       t_grenade_decoygrenade  1.025091

[96 rows x 2 columns]

In [62]:
#lDA is performed to obtain the above scores for each and every column

In [67]:
df1 = df1.sort_values(by = 'lda_coef', ascending = False)

df1

columns  lda_coef
8                t_armor  1.883281
17         t_weapon_ak47  1.835833
7               ct_armor  1.832043
65        t_weapon_sg553  1.745992
40        ct_weapon_m4a4  1.573820
..                   ...       ...
22       ct_weapon_bizon  1.000000
52       ct_weapon_negev  1.000000
60    ct_weapon_sawedoff  1.000000
58  ct_weapon_r8revolver  1.000000
37         t_weapon_m249  1.000000

[96 rows x 2 columns]

In [70]:
top_20 = df1.head(20)
top_20

columns  lda_coef
8                  t_armor  1.883281
17           t_weapon_ak47  1.835833
7                 ct_armor  1.832043
65          t_weapon_sg553  1.745992
40          ct_weapon_m4a4  1.573820
5                ct_health  1.557526
15         t_players_alive  1.441140
6                 t_health  1.387650
20           ct_weapon_awp  1.361280
21            t_weapon_awp  1.291049
4             bomb_planted  1.271102
89  t_grenade_smokegrenade  1.269045
9                 ct_money  1.239307
18           ct_weapon_aug  1.225840
64         ct_weapon_sg553  1.223650
14        ct_players_alive  1.217525
16          ct_weapon_ak47  1.213105
87     t_grenade_flashbang  1.193082
10                 t_money  1.183566
35          t_weapon_glock  1.149905

In [71]:
top_20.index

Index([8, 17, 7, 65, 40, 5, 15, 6, 20, 21, 4, 89, 9, 18, 64, 14, 16, 87, 10,
       35],
      dtype='int64')

In [72]:
imp_cols = top_20.index

In [73]:
x_train

array([[ 0.02190888,  0.04702113,  0.24411537, ..., -0.83044117,
        -0.1641154 , -0.15578773],
       [-0.55793271, -0.16137564, -0.79150888, ..., -0.83044117,
        -0.1641154 , -0.15578773],
       [ 0.38055443,  0.04702113, -0.17013433, ...,  1.56534587,
        -0.1641154 , -0.15578773],
       ...,
       [-1.50374299,  0.88060821, -0.17013433, ..., -0.83044117,
        -0.1641154 , -0.15578773],
       [-1.24461688, -0.36977241, -0.79150888, ..., -0.83044117,
        -0.1641154 , -0.15578773],
       [ 0.38055443,  0.88060821,  0.65836507, ...,  2.16429263,
        -0.1641154 , -0.15578773]])

In [74]:
x_train = x_train[: , imp_cols]

x_train

array([[-0.06200588, -0.94331101,  0.48273624, ..., -1.05222966,
        -0.88598148,  1.06576434],
       [-0.04475887, -0.94331101, -0.12163417, ...,  0.05800621,
        -0.73875891, -0.1609398 ],
       [ 0.98431283,  1.24867805,  0.48273624, ...,  1.72336003,
        -0.53837263,  1.06576434],
       ...,
       [-1.74071501, -0.94331101, -1.30103663, ..., -1.05222966,
        -0.93914518, -2.00099602],
       [-1.16581463, -0.94331101, -1.27756594, ..., -0.49711172,
        -0.88598148, -1.38764395],
       [ 1.12228892,  1.24867805,  0.48273624, ...,  1.72336003,
        -0.40341861, -0.1609398 ]])

In [75]:
x_test

array([[-0.60130817,  1.50579852,  0.45124022, ..., -0.23149441,
        -0.1641154 , -0.15578773],
       [-0.37316454,  1.08900498,  1.69398932, ..., -0.23149441,
        -0.1641154 , -0.15578773],
       [-1.1214381 ,  0.88060821,  0.65836507, ..., -0.23149441,
        -0.1641154 , -0.15578773],
       ...,
       [ 1.50718966, -1.20335949, -1.41288343, ..., -0.83044117,
        -0.1641154 , -0.15578773],
       [ 0.34149774,  0.88060821,  0.03699052, ...,  0.36745235,
        -0.1641154 , -0.15578773],
       [ 1.50794075, -1.20335949, -0.58438403, ..., -0.83044117,
        -0.1641154 , -0.15578773]])

In [76]:
x_test = x_test[: , imp_cols]

x_test

array([[-0.65415328,  0.51801503, -0.14510487, ..., -0.49711172,
        -0.8655339 , -0.77429187],
       [ 0.55888654,  1.24867805,  0.69984018, ..., -1.05222966,
        -0.91460809,  0.45241227],
       [ 0.70261164,  1.24867805, -0.16857557, ...,  0.61312415,
         1.44095304, -0.77429187],
       ...,
       [-1.74071501, -0.94331101, -0.84335807, ..., -1.05222966,
        -0.05989928,  1.06576434],
       [ 1.02455585, -0.21264799,  1.06950363, ...,  1.72336003,
        -0.76738552,  1.06576434],
       [-0.81512539, -0.21264799, -1.27756594, ..., -0.49711172,
         2.81911988,  0.45241227]])

In [77]:
x_train.shape

(93958, 20)

In [78]:
x_test.shape

(23490, 20)

<h4>Model Building</h4>

In [79]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [80]:
lr_model = LogisticRegression()

In [81]:
lr_model.fit(x_train, y_train)

LogisticRegression()

In [82]:
y_predict = lr_model.predict(x_test)

In [84]:
from sklearn.metrics import *

In [85]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.75      0.76      0.76     11488
           1       0.77      0.76      0.76     12002

    accuracy                           0.76     23490
   macro avg       0.76      0.76      0.76     23490
weighted avg       0.76      0.76      0.76     23490



In [86]:
dt_model = DecisionTreeClassifier()

In [87]:
dt_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [88]:
y_pred = dt_model.predict(x_test)

In [89]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81     11488
           1       0.82      0.81      0.81     12002

    accuracy                           0.81     23490
   macro avg       0.81      0.81      0.81     23490
weighted avg       0.81      0.81      0.81     23490



In [90]:
rf_model = RandomForestClassifier()

In [91]:
rf_model.fit(x_train, y_train)

RandomForestClassifier()

In [92]:
y_prdct = rf_model.predict(x_test)

In [93]:
print(classification_report(y_test, y_prdct))

              precision    recall  f1-score   support

           0       0.85      0.86      0.85     11488
           1       0.86      0.85      0.86     12002

    accuracy                           0.86     23490
   macro avg       0.86      0.86      0.86     23490
weighted avg       0.86      0.86      0.86     23490



In [94]:
from sklearn.svm import SVC

In [95]:
svc_model = SVC()

In [97]:
svc_model.fit(x_train, y_train)

SVC()

In [99]:
y_pridct = svc_model.predict(x_test)

In [100]:
print(classification_report(y_test, y_pridct))

              precision    recall  f1-score   support

           0       0.74      0.82      0.78     11488
           1       0.81      0.73      0.77     12002

    accuracy                           0.78     23490
   macro avg       0.78      0.78      0.77     23490
weighted avg       0.78      0.78      0.77     23490

